.RUN FILE = D:\SIT\report_scripts\fexp_logon_batch.txt;
.SET ERROROUT STDOUT;

CREATE VOLATILE TABLE parameters AS 
(
 SELECT ADD_MONTHS((CURRENT_DATE - EXTRACT(DAY FROM CURRENT_DATE)+1),0) -1  AS per_end_dt         
) WITH DATA
PRIMARY INDEX (per_end_dt)
ON COMMIT PRESERVE ROWS;

.IF ERRORCODE <> 0 THEN .EXIT ERRORCODE


INSERT INTO SOCOMM.F_BOLTON_BASE_EDW
(
PER_END_DT,
SVC_NO,
PRODUCT,
EXTERNAL_ID_TYPE,
svc_start_date,
product_start,
BOLTON_RATE_PLAN_CD,
BOLTON_RATE_PLAN_DS,
BASIC_RATE_PLAN_CD,
BASIC_PLAN_DS,
ACCT_NO,
CUSTOMER_NAME,
POST_CD,
NO_OF_X_SVC,
VIP_CODE,
OWNING_COST_CTR,
OWNING_COST_CTR_DV,
CFU,
DLR_CD,
REP_ID,
SALES_CHANL_ID,
RETL_STORE,
ACQ_PARTNR_CMPNY,
SVC_INST_ID,
WORK_ORD_NO,
AR_SUBSCR_NO,
AR_ACCOUNT_NO, 
SRC_CD)
SELECT 
    (SELECT ADD_MONTHS((A.PERD_END_DT - EXTRACT(DAY FROM A.PERD_END_DT)+1),0) -1) AS PER_END_DT1,
    PRIM_RSRC_VALU_TXT AS SVC_NO,
    TRIM(prod_type_ds) ||' '|| TRIM(subs_type_ds ) AS PRODUCT,
    CAST(NULL AS INTEGER) AS EXTERNAL_ID_TYPE,
    ORIG_ACTV_TS AS svc_start_date,
    CAST(CAST(ASSG_PRCE_PLAN_STRT_TS AS VARCHAR(19)) AS TIMESTAMP(0)) AS product_start,
    CAST(CAST(BLTN_BILL_OFFR_ID AS BIGINT) AS VARCHAR(25)) AS BOLTON_RATE_PLAN_CD,
    BLTN_BILL_OFFR_DS AS BOLTON_RATE_PLAN_DS,
    CAST(CAST(MAIN_BILL_OFFR_ID AS BIGINT) AS VARCHAR(25)) AS BASIC_RATE_PLAN_CD,
    MAIN_BILL_OFFR_DS AS BASIC_PLAN_DS,
    CAST(ACCT_ID AS BIGINT) AS ACCT_NO,
    ACCT_NM AS CUSTOMER_NAME,
    ACCT_ZIP_CD AS POST_CD,
    ACCT_MKT_SGMT_SERV_CNT AS NO_OF_X_SVC,
    NULL AS VIP_CODE,
    ACCT_TYPE_CD AS OWNING_COST_CTR,
    ACCT_TYPE_DS AS OWNING_COST_CTR_DV,
    CASE 
        WHEN TRIM(acct_type_cd) ='D' THEN 
            'Consumer'
        WHEN TRIM(acct_type_cd) ='S' THEN 
            'SMB'   
        ELSE 
            'Unknown'
    END AS CFU,
    PROV_DEAL_ID AS DLR_CD,
    PROV_AGNT_LGIN_NM AS REP_ID,
    PROV_SALE_SERV_CHNL_NM AS SALES_CHANL_ID,
    CAST(NULL AS VARCHAR(25)) AS RETL_STORE,
    CAST(NULL AS VARCHAR(25)) AS ACQ_PARTNR_CMPNY,
    CAST(NULL AS VARCHAR(25)) AS SVC_INST_ID,
    CAST(NULL AS VARCHAR(25)) AS WORK_ORD_NO,
    CAST(NULL AS INTEGER) AS AR_SUBSCR_NO,
    CAST(NULL AS INTEGER) AS AR_ACCOUNT_NO, 
    'ED' AS SRC_CD
FROM 
    IOSHARE_EDW.IPS_F_SUBS_BLTN_BASE_MNTH A    
    INNER JOIN PARAMETERS B
    ON PER_END_DT1 = B.PER_END_DT;

.IF ERRORCODE <> 0 THEN .EXIT ERRORCODE

COLLECT STATS ON SOCOMM.F_BOLTON_BASE_EDW COLUMN (SVC_NO);
COLLECT STATS ON SOCOMM.F_BOLTON_BASE_EDW COLUMN (BOLTON_RATE_PLAN_CD);

.IF ERRORCODE <> 0 THEN .EXIT ERRORCODE

INSERT INTO SOCOMM.F_BOLTON_BASE (
    PER_END_DT,
    SVC_NO,
    PRODUCT,
    EXTERNAL_ID_TYPE,
    svc_start_date,
    product_start,
    BOLTON_RATE_PLAN_CD,
    BOLTON_RATE_PLAN_DS,
    BASIC_RATE_PLAN_CD,
    BASIC_PLAN_DS,
    ACCT_NO,
    CUSTOMER_NAME,
    POST_CD,
    NO_OF_X_SVC,
    VIP_CODE,
    OWNING_COST_CTR,
    OWNING_COST_CTR_DV,
    CFU,
    DLR_CD,
    REP_ID,
    SALES_CHANL_ID,
    RETL_STORE,
    ACQ_PARTNR_CMPNY,
    SVC_INST_ID,
    WORK_ORD_NO,
    AR_SUBSCR_NO,
    AR_ACCOUNT_NO, 
    SRC_CD)

SELECT
    PER_END_DT,
    SVC_NO,
    PRODUCT,
    EXTERNAL_ID_TYPE,
    svc_start_date,
    product_start,
    BOLTON_RATE_PLAN_CD,
    BOLTON_RATE_PLAN_DS,
    BASIC_RATE_PLAN_CD,
    BASIC_PLAN_DS,
    ACCT_NO,
    CUSTOMER_NAME,
    POST_CD,
    NO_OF_X_SVC,
    VIP_CODE,
    OWNING_COST_CTR,
    OWNING_COST_CTR_DV,
    CFU,
    DLR_CD,
    REP_ID,
    SALES_CHANL_ID,
    RETL_STORE,
    ACQ_PARTNR_CMPNY,
    SVC_INST_ID,
    WORK_ORD_NO,
    AR_SUBSCR_NO,
    AR_ACCOUNT_NO, 
    SRC_CD
FROM
    SOCOMM.F_BOLTON_BASE_EDW;

.IF ERRORCODE <> 0 THEN .EXIT ERRORCODE

COLLECT STATS ON SOCOMM.F_BOLTON_BASE COLUMN (SVC_NO);
COLLECT STATS ON SOCOMM.F_BOLTON_BASE COLUMN (BOLTON_RATE_PLAN_CD);

.IF ERRORCODE <> 0 THEN .EXIT ERRORCODE

.quit errorcode
.logoff;

